
CREATE TABLE IF NOT EXISTS studio(
    id int primary key not null,
    name text
);
                
INSERT INTO studio (id, name) VALUES (1, 'Pierrot');
INSERT INTO studio (id, name) VALUES (2, 'Kyoto Animation');
INSERT INTO studio (id, name) VALUES (3, 'Gonzo');
INSERT INTO studio (id, name) VALUES (4, 'Bones');
INSERT INTO studio (id, name) VALUES (5, 'Bee Train');
INSERT INTO studio (id, name) VALUES (6, 'Gainax');
INSERT INTO studio (id, name) VALUES (7, 'J.C.Staff');
INSERT INTO studio (id, name) VALUES (8, 'Artland');
INSERT INTO studio (id, name) VALUES (10, 'Production I.G');
INSERT INTO studio (id, name) VALUES (11, 'Madhouse');
INSERT INTO studio (id, name) VALUES (13, 'Studio 4°C');
INSERT INTO studio (id, name) VALUES (14, 'Sunrise');
INSERT INTO studio (id, name) VALUES (18, 'Toei Animation');
INSERT INTO studio (id, name) VALUES (21, 'Studio Ghibli');
INSERT INTO studio (id, name) VALUES (22, 'Nippon Animation');
INSERT INTO studio (id, name) VALUES (24, 'Studio Fantasia');
INSERT INTO studio (id, name) VALUES (27, 'Xebec');
INSERT INTO studio (id, name) VALUES (28, 'OLM');
INSERT INTO studio (id, name) VALUES (29, 'VAP');
INSERT INTO studio (id, name) VALUES (30, 'Ajia-do');
INSERT INTO studio (id, name) VALUES (32, 'Manglobe');
INSERT INTO studio (id, name) VALUES (34, 'HAL Film Maker');
INSERT INTO studio (id, name) VALUES (35, 'Seven Arcs');
INSERT INTO studio (id, name) VALUES (36, 'Gallop');
INSERT INTO studio (id, name) VALUES (37, 'Studio Deen');
INSERT INTO studio (id, name) VALUES (38, 'Arms');
INSERT INTO studio (id, name) VALUES (39, 'Daume');
INSERT INTO studio (id, name) VALUES (41, 'Satelight');
INSERT INTO studio (id, name) VALUES (43, 'ufotable');
INSERT INTO studio (id, name) VALUES (44, 'Shaft');
INSERT INTO studio (id, name) VALUES (47, 'Khara');
INSERT INTO studio (id, name) VALUES (48, 'AIC');
INSERT INTO studio (id, name) VALUES (49, 'Remic');
INSERT INTO studio (id, name) VALUES (50, 'KSS');
INSERT INTO studio (id, name) VALUES (51, 'Diomedéa');
INSERT INTO studio (id, name) VALUES (54, 'Mook Animation');
INSERT INTO studio (id, name) VALUES (56, 'A-1 Pictures');
INSERT INTO studio (id, name) VALUES (59, 'Beat Frog');
INSERT INTO studio (id, name) VALUES (60, 'Actas');
INSERT INTO studio (id, name) VALUES (61, 'Frontier Works');
INSERT INTO studio (id, name) VALUES (62, 'Shogakukan-Shueisha Productions');
INSERT INTO studio (id, name) VALUES (63, 'Trinet Entertainment');
INSERT INTO studio (id, name) VALUES (64, 'Sotsu');
INSERT INTO studio (id, name) VALUES (65, 'Tokyo Movie Shinsha');
INSERT INTO studio (id, name) VALUES (67, 'OB Planning');
INSERT INTO studio (id, name) VALUES (68, 'Mushi Production');
INSERT INTO studio (id, name) VALUES (69, 'Front Line');
INSERT INTO studio (id, name) VALUES (70, 'Nomad');
INSERT INTO studio (id, name) VALUES (72, 'Artmic');
INSERT INTO studio (id, name) VALUES (73, 'TMS Entertainment');
INSERT INTO studio (id, name) VALUES (75, 'Imagin');
INSERT INTO studio (id, name) VALUES (77, 'APPP');
INSERT INTO studio (id, name) VALUES (78, 'Picture Magic');
INSERT INTO studio (id, name) VALUES (79, 'Genco');
INSERT INTO studio (id, name) VALUES (80, 'Trans Arts');
INSERT INTO studio (id, name) VALUES (81, 'Radix');
INSERT INTO studio (id, name) VALUES (82, 'Marvelous Entertainment');
INSERT INTO studio (id, name) VALUES (83, 'AIC Spirits');
INSERT INTO studio (id, name) VALUES (84, 'Studio Rikka');
INSERT INTO studio (id, name) VALUES (86, 'Group TAC');
INSERT INTO studio (id, name) VALUES (88, 'AIC ASTA');
INSERT INTO studio (id, name) VALUES (89, 'BeSTACK');
INSERT INTO studio (id, name) VALUES (91, 'feel.');
INSERT INTO studio (id, name) VALUES (93, 'Studio Flag');
INSERT INTO studio (id, name) VALUES (94, 'Telecom Animation Film');
INSERT INTO studio (id, name) VALUES (95, 'Doga Kobo');
INSERT INTO studio (id, name) VALUES (96, 'Yumeta Company');
INSERT INTO studio (id, name) VALUES (101, 'Studio Hibari');
INSERT INTO studio (id, name) VALUES (103, 'Tatsunoko Production');
INSERT INTO studio (id, name) VALUES (107, 'Plum');
INSERT INTO studio (id, name) VALUES (108, 'Media Factory');
INSERT INTO studio (id, name) VALUES (110, 'Triangle Staff');
INSERT INTO studio (id, name) VALUES (111, 'NHK');
INSERT INTO studio (id, name) VALUES (112, 'Brain''s Base');
INSERT INTO studio (id, name) VALUES (114, 'Studio Matrix');
INSERT INTO studio (id, name) VALUES (117, 'Studio Izena');
INSERT INTO studio (id, name) VALUES (118, 'SynergySP');
INSERT INTO studio (id, name) VALUES (120, 'TNK');
INSERT INTO studio (id, name) VALUES (122, 'Tokyo Kids');
INSERT INTO studio (id, name) VALUES (126, 'Studio Comet');
INSERT INTO studio (id, name) VALUES (131, 'G&G Entertainment');
INSERT INTO studio (id, name) VALUES (132, 'P.A. Works');
INSERT INTO studio (id, name) VALUES (134, 'HoriPro');
INSERT INTO studio (id, name) VALUES (136, 'Vega Entertainment');
INSERT INTO studio (id, name) VALUES (137, 'PPM');
INSERT INTO studio (id, name) VALUES (138, 'Himajin Planning');
INSERT INTO studio (id, name) VALUES (139, 'Nihon Ad Systems');
INSERT INTO studio (id, name) VALUES (141, 'Toei Video');
INSERT INTO studio (id, name) VALUES (144, 'Pony Canyon');
INSERT INTO studio (id, name) VALUES (150, 'Sanrio');
INSERT INTO studio (id, name) VALUES (154, 'E&G Films');
INSERT INTO studio (id, name) VALUES (155, 'animate Film');
INSERT INTO studio (id, name) VALUES (163, 'asread.');
INSERT INTO studio (id, name) VALUES (166, 'Movic');
INSERT INTO studio (id, name) VALUES (168, 'Shelty');
INSERT INTO studio (id, name) VALUES (169, 'Fuji TV');
INSERT INTO studio (id, name) VALUES (170, 'Imagica');
INSERT INTO studio (id, name) VALUES (171, 'A-Line');
INSERT INTO studio (id, name) VALUES (175, 'Planet');
INSERT INTO studio (id, name) VALUES (176, 'Ginga Ya');
INSERT INTO studio (id, name) VALUES (177, 'Studio Kyuuma');
INSERT INTO studio (id, name) VALUES (179, 'A.C.G.T.');
INSERT INTO studio (id, name) VALUES (183, 'Agent 21');
INSERT INTO studio (id, name) VALUES (191, 'Eiken');
INSERT INTO studio (id, name) VALUES (192, 'Shinkuukan');
INSERT INTO studio (id, name) VALUES (193, 'Idea Factory');
INSERT INTO studio (id, name) VALUES (196, 'Production Reed');
INSERT INTO studio (id, name) VALUES (198, 'Gakken');
INSERT INTO studio (id, name) VALUES (199, 'Studio Nue');
INSERT INTO studio (id, name) VALUES (200, 'Tezuka Productions');
INSERT INTO studio (id, name) VALUES (207, 'Magic Bus');
INSERT INTO studio (id, name) VALUES (218, 'Zexcs');
INSERT INTO studio (id, name) VALUES (226, 'Panmedia');
INSERT INTO studio (id, name) VALUES (228, 'Daewon Media');
INSERT INTO studio (id, name) VALUES (229, 'The Answer Studio');
INSERT INTO studio (id, name) VALUES (231, 'CyberConnect2');
INSERT INTO studio (id, name) VALUES (234, 'Oh! Production');
INSERT INTO studio (id, name) VALUES (235, 'Shirogumi');
INSERT INTO studio (id, name) VALUES (239, 'Y.O.U.C');
INSERT INTO studio (id, name) VALUES (242, 'Ashi Productions');
INSERT INTO studio (id, name) VALUES (246, 'Visual 80');
INSERT INTO studio (id, name) VALUES (247, 'Shin-Ei Animation');
INSERT INTO studio (id, name) VALUES (249, 'Robot Communications');
INSERT INTO studio (id, name) VALUES (253, 'Rikuentai');
INSERT INTO studio (id, name) VALUES (254, 'Soft Garage');
INSERT INTO studio (id, name) VALUES (256, 'Studio Kikan');
INSERT INTO studio (id, name) VALUES (258, 'Echo');
INSERT INTO studio (id, name) VALUES (259, 'Kaeruotoko Shokai');
INSERT INTO studio (id, name) VALUES (271, 'Barnum Studio');
INSERT INTO studio (id, name) VALUES (272, 'Studio Kajino');
INSERT INTO studio (id, name) VALUES (273, 'Think Corporation');
INSERT INTO studio (id, name) VALUES (274, 'Suzuki Mirano');
INSERT INTO studio (id, name) VALUES (276, 'DLE');
INSERT INTO studio (id, name) VALUES (280, 'Studio Junio');
INSERT INTO studio (id, name) VALUES (281, 'Kokusai Eigasha');
INSERT INTO studio (id, name) VALUES (285, 'Four Some');
INSERT INTO studio (id, name) VALUES (287, 'David Production');
INSERT INTO studio (id, name) VALUES (288, 'Kaname Productions');
INSERT INTO studio (id, name) VALUES (289, 'ACiD FiLM');
INSERT INTO studio (id, name) VALUES (290, 'Kinema Citrus');
INSERT INTO studio (id, name) VALUES (291, 'CoMix Wave Films');
INSERT INTO studio (id, name) VALUES (292, 'AIC PLUS+');
INSERT INTO studio (id, name) VALUES (293, 'Picograph');
INSERT INTO studio (id, name) VALUES (298, 'Anima');
INSERT INTO studio (id, name) VALUES (299, 'Studio Pastoral');
INSERT INTO studio (id, name) VALUES (300, 'SILVER LINK.');
INSERT INTO studio (id, name) VALUES (304, 'Primastea');
INSERT INTO studio (id, name) VALUES (307, 'Sunwoo Entertainment');
INSERT INTO studio (id, name) VALUES (309, 'GoHands');
INSERT INTO studio (id, name) VALUES (312, 'Life Work');
INSERT INTO studio (id, name) VALUES (314, 'White Fox');
INSERT INTO studio (id, name) VALUES (315, 'DAX Production');
INSERT INTO studio (id, name) VALUES (318, 'WAO World');
INSERT INTO studio (id, name) VALUES (322, 'Bee Media');
INSERT INTO studio (id, name) VALUES (324, 'Directions');
INSERT INTO studio (id, name) VALUES (325, 'Code');
INSERT INTO studio (id, name) VALUES (326, 'Animation 21');
INSERT INTO studio (id, name) VALUES (329, 'Phoenix Entertainment');
INSERT INTO studio (id, name) VALUES (330, 'Kanaban Graphics');
INSERT INTO studio (id, name) VALUES (331, 'Indeprox');
INSERT INTO studio (id, name) VALUES (333, 'TYO Animations');
INSERT INTO studio (id, name) VALUES (334, 'Ordet');
INSERT INTO studio (id, name) VALUES (336, 'JM Animation');
INSERT INTO studio (id, name) VALUES (338, 'Studio Bogey');
INSERT INTO studio (id, name) VALUES (340, 'Future Planet');
INSERT INTO studio (id, name) VALUES (343, 'Puzzle Animation Studio Limited');
INSERT INTO studio (id, name) VALUES (346, 'Hoods Entertainment');
INSERT INTO studio (id, name) VALUES (347, 'PrimeTime');
INSERT INTO studio (id, name) VALUES (349, 'Itasca Studio');
INSERT INTO studio (id, name) VALUES (350, 'The Village of Marchen');
INSERT INTO studio (id, name) VALUES (354, 'Encourage Films');
INSERT INTO studio (id, name) VALUES (358, 'Telescreen');
INSERT INTO studio (id, name) VALUES (361, 'Oxybot');
INSERT INTO studio (id, name) VALUES (363, 'Topcraft');
INSERT INTO studio (id, name) VALUES (364, 'Sovat Theater');
INSERT INTO studio (id, name) VALUES (365, 'PoRO');
INSERT INTO studio (id, name) VALUES (366, 'Tomoyasu Murata Company');
INSERT INTO studio (id, name) VALUES (367, 'Heewon Entertainment');
INSERT INTO studio (id, name) VALUES (370, 'Iyasakadou Film');
INSERT INTO studio (id, name) VALUES (373, 'Panda Factory');
INSERT INTO studio (id, name) VALUES (374, 'Plus Heads');
INSERT INTO studio (id, name) VALUES (375, 'I.Toon');
INSERT INTO studio (id, name) VALUES (377, 'Kuri Jikken Manga Koubou');
INSERT INTO studio (id, name) VALUES (379, 'Avaco Creative Studios');
INSERT INTO studio (id, name) VALUES (381, 'Yamato Works');
INSERT INTO studio (id, name) VALUES (385, 'Tele-Cartoon Japan');
INSERT INTO studio (id, name) VALUES (386, 'Animaruya');
INSERT INTO studio (id, name) VALUES (388, 'Tamura Shigeru Studio');
INSERT INTO studio (id, name) VALUES (389, 'I-move');
INSERT INTO studio (id, name) VALUES (390, 'Tsuchida Productions');
INSERT INTO studio (id, name) VALUES (391, 'Grouper Productions');
INSERT INTO studio (id, name) VALUES (395, 'Oz Inc.');
INSERT INTO studio (id, name) VALUES (397, 'Bridge');
INSERT INTO studio (id, name) VALUES (398, 'Milky Cartoon');
INSERT INTO studio (id, name) VALUES (400, 'Gathering');
INSERT INTO studio (id, name) VALUES (401, 'ChuChu');
INSERT INTO studio (id, name) VALUES (403, 'Tokyo Media Connections');
INSERT INTO studio (id, name) VALUES (404, 'Studio Unicorn');
INSERT INTO studio (id, name) VALUES (405, 'T-Rex');
INSERT INTO studio (id, name) VALUES (406, 'Asahi Production');
INSERT INTO studio (id, name) VALUES (407, 'Studio 9 Maiami');
INSERT INTO studio (id, name) VALUES (409, 'Studio Egg');
INSERT INTO studio (id, name) VALUES (412, 'Studio Wombat');
INSERT INTO studio (id, name) VALUES (413, 'Pastel');
INSERT INTO studio (id, name) VALUES (418, 'Studio Gokumi');
INSERT INTO studio (id, name) VALUES (420, 'ACC Production');
INSERT INTO studio (id, name) VALUES (422, 'Schoolzone');
INSERT INTO studio (id, name) VALUES (423, 'Studio Eromatick');
INSERT INTO studio (id, name) VALUES (425, 'AIC Takarazuka');
INSERT INTO studio (id, name) VALUES (426, 'Filmlink International');
INSERT INTO studio (id, name) VALUES (427, 'Studio G-1Neo');
INSERT INTO studio (id, name) VALUES (429, 'Office AO');
INSERT INTO studio (id, name) VALUES (430, 'Mad Box');
INSERT INTO studio (id, name) VALUES (432, 'Kachidoki Studio');
INSERT INTO studio (id, name) VALUES (433, 'View Works');
INSERT INTO studio (id, name) VALUES (434, 'Synergy Japan');
INSERT INTO studio (id, name) VALUES (435, 'Studio Zero');
INSERT INTO studio (id, name) VALUES (436, 'AIC Build');
INSERT INTO studio (id, name) VALUES (437, 'Kamikaze Douga');
INSERT INTO studio (id, name) VALUES (438, 'Studio Signal');
INSERT INTO studio (id, name) VALUES (439, 'Project No.9');
INSERT INTO studio (id, name) VALUES (441, '8bit');
INSERT INTO studio (id, name) VALUES (442, 'Minami Machi Bugyousho');
INSERT INTO studio (id, name) VALUES (443, 'Studio PuYUKAI');
INSERT INTO studio (id, name) VALUES (444, 'Jinnis Animation Studios');
INSERT INTO studio (id, name) VALUES (450, 'Wako Productions');
INSERT INTO studio (id, name) VALUES (452, 'Knack Productions');
INSERT INTO studio (id, name) VALUES (453, 'Tsuburaya Productions');
INSERT INTO studio (id, name) VALUES (455, 'Palm Studio');
INSERT INTO studio (id, name) VALUES (456, 'Lerche');
INSERT INTO studio (id, name) VALUES (457, 'Venet');
INSERT INTO studio (id, name) VALUES (462, 'Chaos Project');
INSERT INTO studio (id, name) VALUES (463, 'M.S.C');
INSERT INTO studio (id, name) VALUES (466, 'Digital Media Lab');
INSERT INTO studio (id, name) VALUES (471, 'Shanghai Animation Film Studio');
INSERT INTO studio (id, name) VALUES (472, 'Usagi Ou');
INSERT INTO studio (id, name) VALUES (473, 'Ascension');
INSERT INTO studio (id, name) VALUES (474, 'Shogakukan Music & Digital Entertainment');
INSERT INTO studio (id, name) VALUES (475, 'Ishikawa Pro');
INSERT INTO studio (id, name) VALUES (477, 'Kino Production');
INSERT INTO studio (id, name) VALUES (478, 'Studio Blanc.');
INSERT INTO studio (id, name) VALUES (479, 'DOGA Productions');
INSERT INTO studio (id, name) VALUES (481, 'Office Take Off');
INSERT INTO studio (id, name) VALUES (482, 'Automatic Flowers Studio');
INSERT INTO studio (id, name) VALUES (486, 'Digital Frontier');
INSERT INTO studio (id, name) VALUES (489, 'TCJ');
INSERT INTO studio (id, name) VALUES (492, 'Horannabi');
INSERT INTO studio (id, name) VALUES (494, 'Studio Take Off');
INSERT INTO studio (id, name) VALUES (497, 'Studio Gram');
INSERT INTO studio (id, name) VALUES (517, 'Asmik Ace');
INSERT INTO studio (id, name) VALUES (519, 'Collaboration Works');
INSERT INTO studio (id, name) VALUES (521, 'Anpro');
INSERT INTO studio (id, name) VALUES (523, 'SBS TV Production');
INSERT INTO studio (id, name) VALUES (525, 'KAGAYA Studio');
INSERT INTO studio (id, name) VALUES (533, 'N&G Production');
INSERT INTO studio (id, name) VALUES (537, 'SANZIGEN');
INSERT INTO studio (id, name) VALUES (539, 'Ultra Super Pictures');
INSERT INTO studio (id, name) VALUES (541, 'Seven');
INSERT INTO studio (id, name) VALUES (549, 'StudioRF Inc.');
INSERT INTO studio (id, name) VALUES (553, 'Marvy Jack');
INSERT INTO studio (id, name) VALUES (555, 'Studio Chizu');
INSERT INTO studio (id, name) VALUES (557, 'Zyc');
INSERT INTO studio (id, name) VALUES (559, 'Purple Cow Studio Japan');
INSERT INTO studio (id, name) VALUES (563, 'LandQ studios');
INSERT INTO studio (id, name) VALUES (565, 'LMD');
INSERT INTO studio (id, name) VALUES (567, 'D.A.S.T Corporation');
INSERT INTO studio (id, name) VALUES (569, 'MAPPA');
INSERT INTO studio (id, name) VALUES (579, 'AT-2');
INSERT INTO studio (id, name) VALUES (581, 'Sparky Animation');
INSERT INTO studio (id, name) VALUES (583, 'Annapuru');
INSERT INTO studio (id, name) VALUES (587, 'Tomason');
INSERT INTO studio (id, name) VALUES (589, 'Academy Productions');
INSERT INTO studio (id, name) VALUES (591, 'Romanov Films');
INSERT INTO studio (id, name) VALUES (593, 'Egg');
INSERT INTO studio (id, name) VALUES (601, 'lxtl');
INSERT INTO studio (id, name) VALUES (605, 'C2C');
INSERT INTO studio (id, name) VALUES (607, 'RAMS');
INSERT INTO studio (id, name) VALUES (629, 'Studio Sign');
INSERT INTO studio (id, name) VALUES (721, 'GANSIS');
INSERT INTO studio (id, name) VALUES (723, 'Hotline');
INSERT INTO studio (id, name) VALUES (753, 'PRA');
INSERT INTO studio (id, name) VALUES (755, 'Jumondo');
INSERT INTO studio (id, name) VALUES (761, 'Sunny Side Up');
INSERT INTO studio (id, name) VALUES (765, 'Sakura Create');
INSERT INTO studio (id, name) VALUES (767, 'Majin');
INSERT INTO studio (id, name) VALUES (801, 'Nihikime no Dozeu');
INSERT INTO studio (id, name) VALUES (803, 'Trigger');
INSERT INTO studio (id, name) VALUES (805, 'AIC Frontier');
INSERT INTO studio (id, name) VALUES (819, 'Next Media Animation');
INSERT INTO studio (id, name) VALUES (825, 'Fifth Avenue');
INSERT INTO studio (id, name) VALUES (831, 'Otogi Production');
INSERT INTO studio (id, name) VALUES (833, 'Kyotoma');
INSERT INTO studio (id, name) VALUES (839, 'LIDENFILMS');
INSERT INTO studio (id, name) VALUES (848, 'Kazami Gakuen Koushiki Douga-bu');
INSERT INTO studio (id, name) VALUES (850, 'Kenji Studio');
INSERT INTO studio (id, name) VALUES (852, 'Nexus');
INSERT INTO studio (id, name) VALUES (856, 'Charaction');
INSERT INTO studio (id, name) VALUES (858, 'Wit Studio');
INSERT INTO studio (id, name) VALUES (860, 'Triple X');
INSERT INTO studio (id, name) VALUES (866, 'Fanworks');
INSERT INTO studio (id, name) VALUES (878, 'An DerCen');
INSERT INTO studio (id, name) VALUES (884, 'Strawberry Meets Pictures');
INSERT INTO studio (id, name) VALUES (890, 'Karaku');
INSERT INTO studio (id, name) VALUES (894, 'Graphinica');
INSERT INTO studio (id, name) VALUES (896, 'Larx Entertainment');
INSERT INTO studio (id, name) VALUES (898, 'I.Gzwei');
INSERT INTO studio (id, name) VALUES (907, 'AYCO');
INSERT INTO studio (id, name) VALUES (909, 'Studio Kelmadick');
INSERT INTO studio (id, name) VALUES (911, 'Passione');
INSERT INTO studio (id, name) VALUES (917, 'Takahashi Studio');
INSERT INTO studio (id, name) VALUES (921, 'Dynamic Planning');
INSERT INTO studio (id, name) VALUES (929, 'Animation Do');
INSERT INTO studio (id, name) VALUES (931, 'Poncotan');
INSERT INTO studio (id, name) VALUES (939, 'Tama Production');
INSERT INTO studio (id, name) VALUES (945, 'Vasoon Animation');
INSERT INTO studio (id, name) VALUES (949, 'teamKG');
INSERT INTO studio (id, name) VALUES (951, 'NAZ');
INSERT INTO studio (id, name) VALUES (957, 'Connect');
INSERT INTO studio (id, name) VALUES (971, 'Anime R');
INSERT INTO studio (id, name) VALUES (979, 'SPEED');
INSERT INTO studio (id, name) VALUES (989, 'Nihon Hoso Eigasha');
INSERT INTO studio (id, name) VALUES (999, 'Studio Animal');
INSERT INTO studio (id, name) VALUES (1005, 'Oddjob');
INSERT INTO studio (id, name) VALUES (1009, 'Aubec');
INSERT INTO studio (id, name) VALUES (1013, 'Opera House');
INSERT INTO studio (id, name) VALUES (1023, 'Polygon Pictures');
INSERT INTO studio (id, name) VALUES (1025, 'Dongwoo A&E');
INSERT INTO studio (id, name) VALUES (1033, 'Studio Colorido');
INSERT INTO studio (id, name) VALUES (1037, 'Japan Vistec');
INSERT INTO studio (id, name) VALUES (1045, 'Space Neko Company');
INSERT INTO studio (id, name) VALUES (1053, 'Production IMS');
INSERT INTO studio (id, name) VALUES (1055, 'Yamamura Animation, Inc.');
INSERT INTO studio (id, name) VALUES (1063, 'Calf Studio');
INSERT INTO studio (id, name) VALUES (1065, 'Public & Basic');
INSERT INTO studio (id, name) VALUES (1067, 'Rising Force');
INSERT INTO studio (id, name) VALUES (1075, 'C-Station');
INSERT INTO studio (id, name) VALUES (1077, 'MMDGP');
INSERT INTO studio (id, name) VALUES (1087, 'Lay-duce');
INSERT INTO studio (id, name) VALUES (1091, 'Gakken Eigakyoku');
INSERT INTO studio (id, name) VALUES (1093, 'BreakBottle');
INSERT INTO studio (id, name) VALUES (1095, 'Studio Cockpit');
INSERT INTO studio (id, name) VALUES (1099, 'Cyclone Graphics');
INSERT INTO studio (id, name) VALUES (1103, 'TROYCA');
INSERT INTO studio (id, name) VALUES (1107, 'Rabbit Gate');
INSERT INTO studio (id, name) VALUES (1109, 'Orange');
INSERT INTO studio (id, name) VALUES (1111, 'DandeLion Animation Studio');
INSERT INTO studio (id, name) VALUES (1115, 'Studio Korumi');
INSERT INTO studio (id, name) VALUES (1119, 'Shuka');
INSERT INTO studio (id, name) VALUES (1127, 'Studio 3Hz');
INSERT INTO studio (id, name) VALUES (1129, 'Pierrot Plus');
INSERT INTO studio (id, name) VALUES (1131, 'Zero-G Room');
INSERT INTO studio (id, name) VALUES (1133, 'dwarf');
INSERT INTO studio (id, name) VALUES (1135, 'FOREST Hunting One');
INSERT INTO studio (id, name) VALUES (1137, 'SEK Studios');
INSERT INTO studio (id, name) VALUES (1143, 'TOHO animation');
INSERT INTO studio (id, name) VALUES (1151, 'Sanrio Digital');
INSERT INTO studio (id, name) VALUES (1153, 'Image Kei');
INSERT INTO studio (id, name) VALUES (1155, 'Studio Moriken');
INSERT INTO studio (id, name) VALUES (1157, 'Big Bang');
INSERT INTO studio (id, name) VALUES (1165, 'Tri-Slash');
INSERT INTO studio (id, name) VALUES (1169, 'ILCA');
INSERT INTO studio (id, name) VALUES (1171, 'Olive Studio');
INSERT INTO studio (id, name) VALUES (1173, 'Studio Dadashow');
INSERT INTO studio (id, name) VALUES (1181, 'RG Animation Studios');
INSERT INTO studio (id, name) VALUES (1185, '81 Produce');
INSERT INTO studio (id, name) VALUES (1187, 'Ripple Film');
INSERT INTO studio (id, name) VALUES (1189, 'Sola Digital Arts');
INSERT INTO studio (id, name) VALUES (1191, 'Azeta Pictures');
INSERT INTO studio (id, name) VALUES (1193, 'MooGoo');
INSERT INTO studio (id, name) VALUES (1195, 'Creators in Pack');
INSERT INTO studio (id, name) VALUES (1197, 'Steve N'' Steven');
INSERT INTO studio (id, name) VALUES (1203, 'Studio 1st');
INSERT INTO studio (id, name) VALUES (1209, 'Studio A-CAT');
INSERT INTO studio (id, name) VALUES (1217, 'HeART-BIT');
INSERT INTO studio (id, name) VALUES (1229, 'Pie in the sky');
INSERT INTO studio (id, name) VALUES (1231, 'OLM Digital');
INSERT INTO studio (id, name) VALUES (1235, 'I was a Ballerina');
INSERT INTO studio (id, name) VALUES (1237, 'Millepensee');
INSERT INTO studio (id, name) VALUES (1239, 'KeyEast');
INSERT INTO studio (id, name) VALUES (1244, 'Studio VOLN');
INSERT INTO studio (id, name) VALUES (1248, 'Mirai Fusion');
INSERT INTO studio (id, name) VALUES (1249, 'Mirai Film');
INSERT INTO studio (id, name) VALUES (1252, 'Studio Binzo');
INSERT INTO studio (id, name) VALUES (1253, 'Studio GOONEYS');
INSERT INTO studio (id, name) VALUES (1257, 'A-Real');
INSERT INTO studio (id, name) VALUES (1258, 'Bandai Namco Pictures');
INSERT INTO studio (id, name) VALUES (1260, 'Nakamura Production');
INSERT INTO studio (id, name) VALUES (1263, 'Dynamo Pictures');
INSERT INTO studio (id, name) VALUES (1264, 'EMT Squared');
INSERT INTO studio (id, name) VALUES (1265, 'Tomovies');
INSERT INTO studio (id, name) VALUES (1266, 'Studio! Cucuri');
INSERT INTO studio (id, name) VALUES (1268, 'L²Studio');
INSERT INTO studio (id, name) VALUES (1269, 'K-Factory');
INSERT INTO studio (id, name) VALUES (1270, 'Sanctuary');
INSERT INTO studio (id, name) VALUES (1271, 'Assez Finaud Fabric');
INSERT INTO studio (id, name) VALUES (1276, 'HS Pictures Studio');
INSERT INTO studio (id, name) VALUES (1278, 'Signal.MD');
INSERT INTO studio (id, name) VALUES (1279, 'Buemon');
INSERT INTO studio (id, name) VALUES (1281, 'Office DCI');
INSERT INTO studio (id, name) VALUES (1282, 'Arcturus');
INSERT INTO studio (id, name) VALUES (1286, '10Gauge');
INSERT INTO studio (id, name) VALUES (1290, 'Pollyanna Graphics');
INSERT INTO studio (id, name) VALUES (1291, 'KOO-KI');
INSERT INTO studio (id, name) VALUES (1292, 'TUBA');
INSERT INTO studio (id, name) VALUES (1295, 'PINE JAM');
INSERT INTO studio (id, name) VALUES (1296, 'Marza Animation Planet');
INSERT INTO studio (id, name) VALUES (1299, 'AXsiZ');
INSERT INTO studio (id, name) VALUES (1300, 'Office Nobu');
INSERT INTO studio (id, name) VALUES (1301, 'CCTV Animation');
INSERT INTO studio (id, name) VALUES (1304, 'Qualia Animation');
INSERT INTO studio (id, name) VALUES (1306, 'AIC Classic');
INSERT INTO studio (id, name) VALUES (1314, 'Gaina');
INSERT INTO studio (id, name) VALUES (1317, 'Production GoodBook');
INSERT INTO studio (id, name) VALUES (1320, 'Joker Films');
INSERT INTO studio (id, name) VALUES (1322, 'Creative Power Entertaining');
INSERT INTO studio (id, name) VALUES (1324, 'Shimogumi');
INSERT INTO studio (id, name) VALUES (1325, 'Haoliners Animation League');
INSERT INTO studio (id, name) VALUES (1328, 'Decovocal');
INSERT INTO studio (id, name) VALUES (1340, 'Typhoon Graphics');
INSERT INTO studio (id, name) VALUES (1348, 'Sugar Boy');
INSERT INTO studio (id, name) VALUES (1350, 'B.CMAY PICTURES');
INSERT INTO studio (id, name) VALUES (1352, 'Studio Ten Carat');
INSERT INTO studio (id, name) VALUES (1353, 'Issen');
INSERT INTO studio (id, name) VALUES (1356, 'Tonko House');
INSERT INTO studio (id, name) VALUES (1357, 'Craftar Studios');
INSERT INTO studio (id, name) VALUES (1361, 'Darts');
INSERT INTO studio (id, name) VALUES (1362, 'Rabbit Machine');
INSERT INTO studio (id, name) VALUES (1363, 'Marine Entertainment');
INSERT INTO studio (id, name) VALUES (1365, 'Shueisha');
INSERT INTO studio (id, name) VALUES (1368, 'Kazuki Production');
INSERT INTO studio (id, name) VALUES (1369, 'G-Lam');
INSERT INTO studio (id, name) VALUES (1370, 'Sprite Animation Studios');
INSERT INTO studio (id, name) VALUES (1371, 'T.P.O');
INSERT INTO studio (id, name) VALUES (1372, 'Soeishinsha');
INSERT INTO studio (id, name) VALUES (1374, 'Office TakeOut');
INSERT INTO studio (id, name) VALUES (1375, 'Studio Jam');
INSERT INTO studio (id, name) VALUES (1379, 'Zero-G');
INSERT INTO studio (id, name) VALUES (1380, 'domerica');
INSERT INTO studio (id, name) VALUES (1381, 'GEMBA');
INSERT INTO studio (id, name) VALUES (1382, 'Piko Studio');
INSERT INTO studio (id, name) VALUES (1383, 'Studio Live');
INSERT INTO studio (id, name) VALUES (1385, 'Blue Cat');
INSERT INTO studio (id, name) VALUES (1387, 'Neft Film');
INSERT INTO studio (id, name) VALUES (1393, 'Geno Studio');
INSERT INTO studio (id, name) VALUES (1396, 'W-Toon Studio');
INSERT INTO studio (id, name) VALUES (1399, 'Asura Film');
INSERT INTO studio (id, name) VALUES (1407, 'Children''s Playground Entertainment');
INSERT INTO studio (id, name) VALUES (1419, 'GARDEN LODGE');
INSERT INTO studio (id, name) VALUES (1420, 'SIDO LIMITED');
INSERT INTO studio (id, name) VALUES (1421, 'Takara Tomy A.R.T.S');
INSERT INTO studio (id, name) VALUES (1426, 'Studio Meditation With a Pencil');
INSERT INTO studio (id, name) VALUES (1433, 'Ekura Animal');
INSERT INTO studio (id, name) VALUES (1435, 'JCF');
INSERT INTO studio (id, name) VALUES (1436, 'Stingray');
INSERT INTO studio (id, name) VALUES (1437, 'Ishimori Entertainment');
INSERT INTO studio (id, name) VALUES (1440, 'Felix Film');
INSERT INTO studio (id, name) VALUES (1441, 'Mippei Eigeki Kiryuukan');
INSERT INTO studio (id, name) VALUES (1442, 'Mook DLE');
INSERT INTO studio (id, name) VALUES (1444, 'Egg Firm');
INSERT INTO studio (id, name) VALUES (1445, 'Arcs Create');
INSERT INTO studio (id, name) VALUES (1454, 'REALTHING');
INSERT INTO studio (id, name) VALUES (1456, 'Beijing Huihuang Animation Company');
INSERT INTO studio (id, name) VALUES (1460, 'Coastline Animation Studio');
INSERT INTO studio (id, name) VALUES (1462, 'B&T');
INSERT INTO studio (id, name) VALUES (1463, 'Anime Antenna Iinkai');
INSERT INTO studio (id, name) VALUES (1464, 'Hiro Media');
INSERT INTO studio (id, name) VALUES (1465, 'Beijing Enlight Pictures');
INSERT INTO studio (id, name) VALUES (1471, 'Platinum Vision');
INSERT INTO studio (id, name) VALUES (1472, 'Myung Films');
INSERT INTO studio (id, name) VALUES (1473, 'Odolttogi');
INSERT INTO studio (id, name) VALUES (1476, 'Shochiku Animation Institute');
INSERT INTO studio (id, name) VALUES (1479, 'Studio Core');
INSERT INTO studio (id, name) VALUES (1485, 'Light Chaser Animation Studios');
INSERT INTO studio (id, name) VALUES (1487, 'Bouncy');
INSERT INTO studio (id, name) VALUES (1489, 'Ripromo');
INSERT INTO studio (id, name) VALUES (1504, 'Studio Z5');
INSERT INTO studio (id, name) VALUES (1505, 'Studio March');
INSERT INTO studio (id, name) VALUES (1509, 'Studio World');
INSERT INTO studio (id, name) VALUES (1512, 'Dai-Ichi Douga');
INSERT INTO studio (id, name) VALUES (1514, 'Tengu Kobo');
INSERT INTO studio (id, name) VALUES (1517, 'Jinnan Studio');
INSERT INTO studio (id, name) VALUES (1521, 'Studio Elle');
INSERT INTO studio (id, name) VALUES (1522, 'Echoes');
INSERT INTO studio (id, name) VALUES (1523, 'Studio Ponoc');
INSERT INTO studio (id, name) VALUES (1525, 'Moss Design Unit');
INSERT INTO studio (id, name) VALUES (1527, 'Image House');
INSERT INTO studio (id, name) VALUES (1529, 'Studio M2');
INSERT INTO studio (id, name) VALUES (1530, 'Emon');
INSERT INTO studio (id, name) VALUES (1531, 'Flavors Soft');
INSERT INTO studio (id, name) VALUES (1536, 'Namu Animation');
INSERT INTO studio (id, name) VALUES (1547, 'Blade');
INSERT INTO studio (id, name) VALUES (1558, 'TOCSIS');
INSERT INTO studio (id, name) VALUES (1560, 'Yaoyorozu');
INSERT INTO studio (id, name) VALUES (1562, 'Team YokkyuFuman');
INSERT INTO studio (id, name) VALUES (1567, 'Nut');
INSERT INTO studio (id, name) VALUES (1569, 'Seven Arcs Pictures');
INSERT INTO studio (id, name) VALUES (1572, 'XFLAG');
INSERT INTO studio (id, name) VALUES (1573, 'XFLAG Pictures');
INSERT INTO studio (id, name) VALUES (1575, 'DR Movie');
INSERT INTO studio (id, name) VALUES (1591, 'Science SARU');
INSERT INTO studio (id, name) VALUES (1592, 'Kamio Japan');
INSERT INTO studio (id, name) VALUES (1593, 'Success Corp.');
INSERT INTO studio (id, name) VALUES (1596, 'Will Palette');
INSERT INTO studio (id, name) VALUES (1618, 'Rockwell Eyes');
INSERT INTO studio (id, name) VALUES (1638, 'Tsukimidou');
INSERT INTO studio (id, name) VALUES (1639, 'Chiptune');
INSERT INTO studio (id, name) VALUES (1642, 'Circle Tribute');
INSERT INTO studio (id, name) VALUES (1650, 'Twilight Studio');
INSERT INTO studio (id, name) VALUES (1661, 'drop');
INSERT INTO studio (id, name) VALUES (1662, 'Creators Dot Com');
INSERT INTO studio (id, name) VALUES (1667, 'Foch Film');
INSERT INTO studio (id, name) VALUES (1668, 'Karasfilms');
INSERT INTO studio (id, name) VALUES (1669, 'production doA');
INSERT INTO studio (id, name) VALUES (1673, 'DMM.futureworks');
INSERT INTO studio (id, name) VALUES (1678, 'Yuhodo');
INSERT INTO studio (id, name) VALUES (1684, 'THINKR');
INSERT INTO studio (id, name) VALUES (1687, 'Yokohama Animation Laboratory');
INSERT INTO studio (id, name) VALUES (1690, 'Imagineer');
INSERT INTO studio (id, name) VALUES (1691, 'Studio UGOKI');
INSERT INTO studio (id, name) VALUES (1692, 'Revoroot');
INSERT INTO studio (id, name) VALUES (1693, 'Studio Flad');
INSERT INTO studio (id, name) VALUES (1694, 'AZ Creative');
INSERT INTO studio (id, name) VALUES (1705, 'Studio Khronos');
INSERT INTO studio (id, name) VALUES (1717, 'Onionskin');
INSERT INTO studio (id, name) VALUES (1722, 'Bibury Animation Studios');
INSERT INTO studio (id, name) VALUES (1723, 'Anime Beans');
INSERT INTO studio (id, name) VALUES (1724, 'Studio OX');
INSERT INTO studio (id, name) VALUES (1725, 'Minakata Laboratory');
INSERT INTO studio (id, name) VALUES (1726, 'Three-d');
INSERT INTO studio (id, name) VALUES (1746, 'Pops Inc.');
INSERT INTO studio (id, name) VALUES (1747, 'Twin Engine');
INSERT INTO studio (id, name) VALUES (1750, 'Studio CA');
INSERT INTO studio (id, name) VALUES (1751, 'pH Studio');
INSERT INTO studio (id, name) VALUES (1753, 'D & D Pictures');
INSERT INTO studio (id, name) VALUES (1754, 'Meruhensha');
INSERT INTO studio (id, name) VALUES (1759, 'Lilix');
INSERT INTO studio (id, name) VALUES (1762, 'Piso Studio');
INSERT INTO studio (id, name) VALUES (1763, 'Studio Nanahoshi');
INSERT INTO studio (id, name) VALUES (1764, 'Picona');
INSERT INTO studio (id, name) VALUES (1766, 'Husio Studio');
INSERT INTO studio (id, name) VALUES (1767, 'iDRAGONS Creative Studio');
INSERT INTO studio (id, name) VALUES (1768, 'Sparkly Key Animation Studio');
INSERT INTO studio (id, name) VALUES (1769, 'helo.inc');
INSERT INTO studio (id, name) VALUES (1770, 'KIZAWA Studio');
INSERT INTO studio (id, name) VALUES (1771, 'Pb Animation Co. Ltd.');
INSERT INTO studio (id, name) VALUES (1772, 'Wawayu Animation');
INSERT INTO studio (id, name) VALUES (1773, 'KJJ Animation');
INSERT INTO studio (id, name) VALUES (1774, 'LAN Studio');
INSERT INTO studio (id, name) VALUES (1776, 'Studio Mir');
INSERT INTO studio (id, name) VALUES (1793, 'Happy Elements');
INSERT INTO studio (id, name) VALUES (1794, 'EKACHI EPILKA');
INSERT INTO studio (id, name) VALUES (1795, 'CUCURI');
INSERT INTO studio (id, name) VALUES (1796, 'Saber Works');
INSERT INTO studio (id, name) VALUES (1797, 'NHK Enterprises');
INSERT INTO studio (id, name) VALUES (1800, 'Marui Group');
INSERT INTO studio (id, name) VALUES (1804, 'Nice Boat Animation');
INSERT INTO studio (id, name) VALUES (1805, 'Thundray');
INSERT INTO studio (id, name) VALUES (1807, '2:10 AM Animation');
INSERT INTO studio (id, name) VALUES (1808, 'CG Year');
INSERT INTO studio (id, name) VALUES (1809, 'October Media');
INSERT INTO studio (id, name) VALUES (1810, 'Mili Pictures');
INSERT INTO studio (id, name) VALUES (1811, 'Boyan Pictures');
INSERT INTO studio (id, name) VALUES (1812, 'Imagica Imageworks');
INSERT INTO studio (id, name) VALUES (1813, 'Studio Lings');
INSERT INTO studio (id, name) VALUES (1814, 'Studio Hakk');
INSERT INTO studio (id, name) VALUES (1827, 'Motion Magic');
INSERT INTO studio (id, name) VALUES (1828, 'Lapin Track');
INSERT INTO studio (id, name) VALUES (1829, 'Lesprit');
INSERT INTO studio (id, name) VALUES (1830, 'Seven Stone Entertainment');
INSERT INTO studio (id, name) VALUES (1831, 'Colored Pencil Animation Japan');
INSERT INTO studio (id, name) VALUES (1832, 'GRIZZLY');
INSERT INTO studio (id, name) VALUES (1835, 'CloverWorks');
INSERT INTO studio (id, name) VALUES (1836, 'SELFISH');
INSERT INTO studio (id, name) VALUES (1837, 'G-angle');
INSERT INTO studio (id, name) VALUES (1838, '33 Collective');
INSERT INTO studio (id, name) VALUES (1839, 'Studio Ppuri');
INSERT INTO studio (id, name) VALUES (1842, 'Urban Product');
INSERT INTO studio (id, name) VALUES (1843, 'TriF Studio');
INSERT INTO studio (id, name) VALUES (1844, 'Shanghai Hippo Animation');
INSERT INTO studio (id, name) VALUES (1845, 'Guton Animation Studio');
INSERT INTO studio (id, name) VALUES (1846, 'Tokyo Movie');
INSERT INTO studio (id, name) VALUES (1847, 'Square Enix Visual Works');
INSERT INTO studio (id, name) VALUES (1848, 'Dancing CG Studio');
INSERT INTO studio (id, name) VALUES (1849, 'MASTER LIGHTS');
INSERT INTO studio (id, name) VALUES (1851, 'Jumonji');
INSERT INTO studio (id, name) VALUES (1853, 'Saetta');
INSERT INTO studio (id, name) VALUES (1854, 'monofilmo');
INSERT INTO studio (id, name) VALUES (1857, 'Geek Toys');
INSERT INTO studio (id, name) VALUES (1860, 'Magia Doraglier');
INSERT INTO studio (id, name) VALUES (1861, 'Animation Planet');
INSERT INTO studio (id, name) VALUES (1864, 'Ezόla');
INSERT INTO studio (id, name) VALUES (1866, 'Grom');
INSERT INTO studio (id, name) VALUES (1867, 'Aurum Production');
INSERT INTO studio (id, name) VALUES (1871, 'Studio W.Baba');
INSERT INTO studio (id, name) VALUES (1872, 'P.I.C.S.');
INSERT INTO studio (id, name) VALUES (1873, 'Silver');
INSERT INTO studio (id, name) VALUES (1874, 'Arvo Animation');
INSERT INTO studio (id, name) VALUES (1876, 'CLAP');
INSERT INTO studio (id, name) VALUES (1879, 'Dangun Pictures');
INSERT INTO studio (id, name) VALUES (1882, 'UWAN Pictures');
INSERT INTO studio (id, name) VALUES (1887, 'Brio Animation');
INSERT INTO studio (id, name) VALUES (1890, 'Tear Studio');
INSERT INTO studio (id, name) VALUES (1892, 'Sublimation');
INSERT INTO studio (id, name) VALUES (1893, 'CygamesPictures');
INSERT INTO studio (id, name) VALUES (1897, 'Ankama Animations');
INSERT INTO studio (id, name) VALUES (1903, 'IMAGICA Lab.');
INSERT INTO studio (id, name) VALUES (1910, 'Sega Interactive');
INSERT INTO studio (id, name) VALUES (1927, 'Studio Crocodile');
INSERT INTO studio (id, name) VALUES (1932, 'Speed Inc.');
INSERT INTO studio (id, name) VALUES (1934, 'Saigo no Shudan');
INSERT INTO studio (id, name) VALUES (1936, 'Liberty Animation Studio');
INSERT INTO studio (id, name) VALUES (1937, 'MAT');
INSERT INTO studio (id, name) VALUES (1939, 'Alpha Animation');
INSERT INTO studio (id, name) VALUES (1943, 'Idol');
INSERT INTO studio (id, name) VALUES (1944, 'Samsara Animation Studio');
INSERT INTO studio (id, name) VALUES (1945, 'Lide');
INSERT INTO studio (id, name) VALUES (1947, 'Kate Arrow');
INSERT INTO studio (id, name) VALUES (1949, 'Anon Pictures');
INSERT INTO studio (id, name) VALUES (1951, 'ANIDO FILM');
INSERT INTO studio (id, name) VALUES (1952, 'Animation Staff Room');
INSERT INTO studio (id, name) VALUES (1953, 'W+K Tokyo');
INSERT INTO studio (id, name) VALUES (1954, 'Welz Animation Studios');
INSERT INTO studio (id, name) VALUES (1958, 'YHKT Entertainment');
INSERT INTO studio (id, name) VALUES (1959, 'Green Monster Team');
INSERT INTO studio (id, name) VALUES (1960, 'StoryRiders Co. Ltd.');
INSERT INTO studio (id, name) VALUES (1961, 'Creatures Inc.');
INSERT INTO studio (id, name) VALUES (1966, 'Arch');
INSERT INTO studio (id, name) VALUES (1967, 'Drive');
INSERT INTO studio (id, name) VALUES (1968, 'Studio Hokiboshi');
INSERT INTO studio (id, name) VALUES (1969, 'V-sign');
INSERT INTO studio (id, name) VALUES (1970, 'Wolf Smoke Studio');
INSERT INTO studio (id, name) VALUES (1971, 'Gainax Kyoto');
INSERT INTO studio (id, name) VALUES (1972, 'HOTZIPANG');
INSERT INTO studio (id, name) VALUES (1973, 'Monster''s Egg');
INSERT INTO studio (id, name) VALUES (1974, 'ENGI');
INSERT INTO studio (id, name) VALUES (1975, 'Qubic Pictures');
INSERT INTO studio (id, name) VALUES (1976, 'CGCG Studio');
INSERT INTO studio (id, name) VALUES (1978, 'Maho Film');
INSERT INTO studio (id, name) VALUES (1979, 'Suna Kouhou');
INSERT INTO studio (id, name) VALUES (1980, 'Big Firebird Culture');
INSERT INTO studio (id, name) VALUES (1982, 'LIDENFILMS Osaka Studio');
INSERT INTO studio (id, name) VALUES (1983, 'Anima&Co.');
INSERT INTO studio (id, name) VALUES (1984, 'Bakken Record');
INSERT INTO studio (id, name) VALUES (1991, 'Enishiya');
INSERT INTO studio (id, name) VALUES (1993, 'Studio Bind');
INSERT INTO studio (id, name) VALUES (1995, 'Live2D Creative Studio');
INSERT INTO studio (id, name) VALUES (1997, 'Studio Kai');
INSERT INTO studio (id, name) VALUES (1998, 'Studio Signpost');
INSERT INTO studio (id, name) VALUES (1999, 'Albacrow');
INSERT INTO studio (id, name) VALUES (2004, 'Sunrise Beyond');
INSERT INTO studio (id, name) VALUES (2009, 'Yostar Pictures');
INSERT INTO studio (id, name) VALUES (2010, 'Nippon Ramayana Film Co.');
INSERT INTO studio (id, name) VALUES (2011, 'Yonago Gainax');
INSERT INTO studio (id, name) VALUES (2013, 'Peak Hunt');
INSERT INTO studio (id, name) VALUES (2014, 'Nur');
INSERT INTO studio (id, name) VALUES (2020, 'Ark');
INSERT INTO studio (id, name) VALUES (2022, 'TYMOTE');
INSERT INTO studio (id, name) VALUES (2023, 'Spoon');
INSERT INTO studio (id, name) VALUES (2027, 'Team TillDawn');
INSERT INTO studio (id, name) VALUES (2029, 'Earth Design Works');
INSERT INTO studio (id, name) VALUES (2032, 'WHOPPERS');
INSERT INTO studio (id, name) VALUES (2033, 'FILMONY');
INSERT INTO studio (id, name) VALUES (2034, 'Akatsuki');
INSERT INTO studio (id, name) VALUES (2037, 'Okuruto Noboru');
INSERT INTO studio (id, name) VALUES (2040, 'Maro Studio');
INSERT INTO studio (id, name) VALUES (2041, 'Enjin Productions');
INSERT INTO studio (id, name) VALUES (2042, 'Ruo Hong Culture');
INSERT INTO studio (id, name) VALUES (2046, 'Dazzling Star');
INSERT INTO studio (id, name) VALUES (2047, 'Pancake');
INSERT INTO studio (id, name) VALUES (2048, 'ASK Animation Studio');
INSERT INTO studio (id, name) VALUES (2050, 'Trash Studio');
INSERT INTO studio (id, name) VALUES (2051, 'Studio Coa');
INSERT INTO studio (id, name) VALUES (2052, 'Wolfsbane');
INSERT INTO studio (id, name) VALUES (2053, 'l-a-unch・BOX');
INSERT INTO studio (id, name) VALUES (2054, 'MORIE Inc.');
INSERT INTO studio (id, name) VALUES (2055, 'BYMENT');
INSERT INTO studio (id, name) VALUES (2056, 'DRAWIZ');
INSERT INTO studio (id, name) VALUES (2057, 'Toho Interactive Animation');
INSERT INTO studio (id, name) VALUES (2058, 'Shengying Animation');
INSERT INTO studio (id, name) VALUES (2059, 'Suoyi Technology');
INSERT INTO studio (id, name) VALUES (2060, 'Wulifang');
INSERT INTO studio (id, name) VALUES (2061, 'Kaca Entertainment');
INSERT INTO studio (id, name) VALUES (2063, 'Spell Bound');
INSERT INTO studio (id, name) VALUES (2064, 'Mokai Technology');
INSERT INTO studio (id, name) VALUES (2065, 'Original Force');
INSERT INTO studio (id, name) VALUES (2067, 'Flat Studio');
INSERT INTO studio (id, name) VALUES (2068, 'Ai Si Animation Studio');
INSERT INTO studio (id, name) VALUES (2069, 'Making Animation');
INSERT INTO studio (id, name) VALUES (2070, 'Wei Chuang Jiang Xin');
INSERT INTO studio (id, name) VALUES (2071, 'AQUA ARIS');
INSERT INTO studio (id, name) VALUES (2073, 'Painting Dream');
INSERT INTO studio (id, name) VALUES (2075, 'Taomee');
INSERT INTO studio (id, name) VALUES (2076, 'Fenz');
INSERT INTO studio (id, name) VALUES (2078, 'HIDEHOMARE');
INSERT INTO studio (id, name) VALUES (2079, 'Animation Lab Japan');
INSERT INTO studio (id, name) VALUES (2080, 'Super Normal Studio');
INSERT INTO studio (id, name) VALUES (2081, 'JJJOY Animation Studios');
INSERT INTO studio (id, name) VALUES (2082, 'Benlai Pictures');
INSERT INTO studio (id, name) VALUES (2084, 'Tong Ming Xuan');
INSERT INTO studio (id, name) VALUES (2085, 'Acca effe');
INSERT INTO studio (id, name) VALUES (2086, 'Giga Production');
INSERT INTO studio (id, name) VALUES (2091, 'Xanthus Media');
INSERT INTO studio (id, name) VALUES (2097, 'HORNETS');
INSERT INTO studio (id, name) VALUES (2114, 'Ether Kitten');
INSERT INTO studio (id, name) VALUES (2115, 'Gosay Studio');
INSERT INTO studio (id, name) VALUES (2122, 'PERIMETRON');
INSERT INTO studio (id, name) VALUES (2123, 'foodunited.');
INSERT INTO studio (id, name) VALUES (2125, 'LICO');
INSERT INTO studio (id, name) VALUES (2126, 'Red Dog Culture House');
INSERT INTO studio (id, name) VALUES (2129, 'Visual Flight');
INSERT INTO studio (id, name) VALUES (2130, 'Studio Shelter');
INSERT INTO studio (id, name) VALUES (2133, 'Djinn Power');
INSERT INTO studio (id, name) VALUES (2134, 'Studio CANDY BOX');
INSERT INTO studio (id, name) VALUES (2136, 'Ten Tails Animation');
INSERT INTO studio (id, name) VALUES (2137, '1IN');
INSERT INTO studio (id, name) VALUES (2140, 'Qianqi Animation');
INSERT INTO studio (id, name) VALUES (2141, 'TANOsim');
INSERT INTO studio (id, name) VALUES (2142, 'LEVELS');
INSERT INTO studio (id, name) VALUES (2143, 'LX Animation Studio');
INSERT INTO studio (id, name) VALUES (2144, 'BloomZ');
INSERT INTO studio (id, name) VALUES (2151, 'Ekakiya');
INSERT INTO studio (id, name) VALUES (2157, 'Production +h.');
INSERT INTO studio (id, name) VALUES (2158, 'Durufix');
INSERT INTO studio (id, name) VALUES (2159, 'Composition Inc.');
INSERT INTO studio (id, name) VALUES (2161, 'Suspenders');
INSERT INTO studio (id, name) VALUES (2162, 'Maxilla');
INSERT INTO studio (id, name) VALUES (2163, 'Teatro Nishi Tokyo Studio');
INSERT INTO studio (id, name) VALUES (2164, 'Super Brain');
INSERT INTO studio (id, name) VALUES (2167, 'Hololive Production');
INSERT INTO studio (id, name) VALUES (2169, 'Studio 88');
INSERT INTO studio (id, name) VALUES (2171, 'Paper Animation');
INSERT INTO studio (id, name) VALUES (2172, 'Original Dream');
INSERT INTO studio (id, name) VALUES (2175, 'Garden Culture');
INSERT INTO studio (id, name) VALUES (2177, 'Mimoid');
INSERT INTO studio (id, name) VALUES (2178, 'Tecarat');
INSERT INTO studio (id, name) VALUES (2179, 'FIREBUG');
INSERT INTO studio (id, name) VALUES (2183, 'Keica');
INSERT INTO studio (id, name) VALUES (2184, 'The Monk Studios');
INSERT INTO studio (id, name) VALUES (2188, 'Marone');
INSERT INTO studio (id, name) VALUES (2191, 'BUILD DREAM');
INSERT INTO studio (id, name) VALUES (2192, 'Hai An Xian Donghua Gongzuo Shi');
INSERT INTO studio (id, name) VALUES (2193, 'ORENDA');
INSERT INTO studio (id, name) VALUES (2194, 'Yi Chen Animation');
INSERT INTO studio (id, name) VALUES (2195, 'PONOS Corporation');
INSERT INTO studio (id, name) VALUES (2196, 'Studio DURIAN');
INSERT INTO studio (id, name) VALUES (2201, 'Studio Palette');
INSERT INTO studio (id, name) VALUES (2204, 'OZ');
INSERT INTO studio (id, name) VALUES (2205, 'Studio Kafka');
INSERT INTO studio (id, name) VALUES (2206, 'Xuni Ying Ye');
INSERT INTO studio (id, name) VALUES (2207, 'Poly Animation');
INSERT INTO studio (id, name) VALUES (2208, 'Taikong Works');
INSERT INTO studio (id, name) VALUES (2209, 'Reiki Eyes Animation');
INSERT INTO studio (id, name) VALUES (2210, 'Jichitai Anime');
INSERT INTO studio (id, name) VALUES (2211, 'Lingsanwu Animation');
INSERT INTO studio (id, name) VALUES (2212, 'Tsumugi Akita Animation Lab');
INSERT INTO studio (id, name) VALUES (2213, 'Magma Studio');
INSERT INTO studio (id, name) VALUES (2214, 'Takun Manga Box');
INSERT INTO studio (id, name) VALUES (2216, 'CMAY Animation');
INSERT INTO studio (id, name) VALUES (2226, 'Gambit');
INSERT INTO studio (id, name) VALUES (2233, 'Starry Cube');
INSERT INTO studio (id, name) VALUES (2239, 'Transcendence Picture');
INSERT INTO studio (id, name) VALUES (2240, 'Studio Daisy');
INSERT INTO studio (id, name) VALUES (2241, 'Dawn Animation');
INSERT INTO studio (id, name) VALUES (2243, 'Quebico');
INSERT INTO studio (id, name) VALUES (2244, 'Studio Gohan');
INSERT INTO studio (id, name) VALUES (2246, 'studio MOTHER');
INSERT INTO studio (id, name) VALUES (2247, 'Delight Animation');
INSERT INTO studio (id, name) VALUES (2248, 'Indivision');
INSERT INTO studio (id, name) VALUES (2249, 'Flagship Line');
INSERT INTO studio (id, name) VALUES (2250, 'Spooky graphic');
INSERT INTO studio (id, name) VALUES (2251, 'TthunDer Animation');
INSERT INTO studio (id, name) VALUES (2252, 'Studio Kingyoiro');
INSERT INTO studio (id, name) VALUES (2253, 'miHoYoAnime');
INSERT INTO studio (id, name) VALUES (2256, 'Kitty Film Mitaka Studio');
INSERT INTO studio (id, name) VALUES (2257, 'XEBEC M2');
INSERT INTO studio (id, name) VALUES (2258, 'Sharefun Studio');
INSERT INTO studio (id, name) VALUES (2264, '5 Inc.');
INSERT INTO studio (id, name) VALUES (2265, 'ARECT');
INSERT INTO studio (id, name) VALUES (2266, 'Planet Nemo Animation');
INSERT INTO studio (id, name) VALUES (2267, 'MMT Technology');
INSERT INTO studio (id, name) VALUES (2268, 'Point Pictures');
INSERT INTO studio (id, name) VALUES (2269, 'New Generation');
INSERT INTO studio (id, name) VALUES (2270, 'Wise Guy');
INSERT INTO studio (id, name) VALUES (2274, 'Qiying Animation');
INSERT INTO studio (id, name) VALUES (2275, 'Drawing and Manual');
INSERT INTO studio (id, name) VALUES (2276, 'Project Team Sarah');
INSERT INTO studio (id, name) VALUES (2277, 'Network Kouenji Studio');
INSERT INTO studio (id, name) VALUES (2281, 'Rocen');
INSERT INTO studio (id, name) VALUES (2282, 'Studio Guts');
INSERT INTO studio (id, name) VALUES (2284, 'SJYNEXCUS');
INSERT INTO studio (id, name) VALUES (2288, 'Qzil.la');
INSERT INTO studio (id, name) VALUES (2292, 'Toei Advertising');
INSERT INTO studio (id, name) VALUES (2294, 'AHA Entertainment');
INSERT INTO studio (id, name) VALUES (2295, 'Story Effect');
INSERT INTO studio (id, name) VALUES (2296, 'Studio Nuck');
INSERT INTO studio (id, name) VALUES (2298, 'AtelierPontdarc');
INSERT INTO studio (id, name) VALUES (2299, 'GIFTanimation');
INSERT INTO studio (id, name) VALUES (2300, 'Studio Jemi');
INSERT INTO studio (id, name) VALUES (2301, 'Borutong');
INSERT INTO studio (id, name) VALUES (2302, 'Nostalook');
INSERT INTO studio (id, name) VALUES (2303, 'Noovo');
INSERT INTO studio (id, name) VALUES (2304, 'TrioPen Studio');
INSERT INTO studio (id, name) VALUES (2305, 'Fukushima Gaina');
INSERT INTO studio (id, name) VALUES (2306, 'LIDENFILMS Kyoto Studio');
INSERT INTO studio (id, name) VALUES (2310, 'Paper Plane Animation Studio');
INSERT INTO studio (id, name) VALUES (2311, 'Gyorai Eizo Inc.');
INSERT INTO studio (id, name) VALUES (2313, 'studio hb');
INSERT INTO studio (id, name) VALUES (2314, 'Quad');
INSERT INTO studio (id, name) VALUES (2315, 'Office No. 8');
INSERT INTO studio (id, name) VALUES (2316, 'Maboroshi Koubou');
INSERT INTO studio (id, name) VALUES (2317, 'Dream Entertainment');
INSERT INTO studio (id, name) VALUES (2318, 'ORADA COMPANY');
INSERT INTO studio (id, name) VALUES (2319, 'Datama Film');
INSERT INTO studio (id, name) VALUES (2320, 'Inugoya');
INSERT INTO studio (id, name) VALUES (2321, 'Production D.M.H');
INSERT INTO studio (id, name) VALUES (2322, 'Mousou Senka');
INSERT INTO studio (id, name) VALUES (2323, 'Cafe de Jeilhouse');
INSERT INTO studio (id, name) VALUES (2325, 'Bibury Animation CG');
INSERT INTO studio (id, name) VALUES (2327, 'Studio Boogie Nights');
INSERT INTO studio (id, name) VALUES (2328, 'Sonsan Kikaku');
INSERT INTO studio (id, name) VALUES (2329, 'Shinjukuza');
INSERT INTO studio (id, name) VALUES (2330, 'Meltdown');
INSERT INTO studio (id, name) VALUES (2331, 'Shura');
INSERT INTO studio (id, name) VALUES (2332, 'Shion');
INSERT INTO studio (id, name) VALUES (2333, 'Space-X');
INSERT INTO studio (id, name) VALUES (2334, 'Mouse');
INSERT INTO studio (id, name) VALUES (2335, 'Shindeban Film');
INSERT INTO studio (id, name) VALUES (2336, 'Lead');
INSERT INTO studio (id, name) VALUES (2337, 'Studio Soul');
INSERT INTO studio (id, name) VALUES (2338, 'Studio Ten');
INSERT INTO studio (id, name) VALUES (2339, 'Melissa');
INSERT INTO studio (id, name) VALUES (2340, 'Cutie Bee');
INSERT INTO studio (id, name) VALUES (2341, 'Studio Prokion');
INSERT INTO studio (id, name) VALUES (2342, 'PP Project');
INSERT INTO studio (id, name) VALUES (2345, 'Onion Studio');
INSERT INTO studio (id, name) VALUES (2346, 'Alice Production');
INSERT INTO studio (id, name) VALUES (2347, 'IKK Room');
INSERT INTO studio (id, name) VALUES (2348, 'KKC Animation Production');
INSERT INTO studio (id, name) VALUES (2349, 'Potato House');
INSERT INTO studio (id, name) VALUES (2350, 'Kantou Douga Kai');
INSERT INTO studio (id, name) VALUES (2351, 'Studio Gadget');
INSERT INTO studio (id, name) VALUES (2352, 'Tryforce');
INSERT INTO studio (id, name) VALUES (2353, 'P core');
INSERT INTO studio (id, name) VALUES (2355, 'Alfred Imageworks');
INSERT INTO studio (id, name) VALUES (2356, 'Kung Fu Frog Animation');
INSERT INTO studio (id, name) VALUES (2358, 'Big Wing');
INSERT INTO studio (id, name) VALUES (2359, 'Aiko');
INSERT INTO studio (id, name) VALUES (2360, 'Amarcord');
INSERT INTO studio (id, name) VALUES (2361, 'Okumaza');
INSERT INTO studio (id, name) VALUES (2362, 'Aiti St.');
INSERT INTO studio (id, name) VALUES (2363, 'JOF');
INSERT INTO studio (id, name) VALUES (2365, 'MI');
INSERT INTO studio (id, name) VALUES (2366, 'Kigumi');
INSERT INTO studio (id, name) VALUES (2370, 'Hayabusa Film');
INSERT INTO studio (id, name) VALUES (2371, 'Planet Cartoon');
INSERT INTO studio (id, name) VALUES (2372, 'Flint Sugar');
INSERT INTO studio (id, name) VALUES (2374, 'Momoi Planning');
INSERT INTO studio (id, name) VALUES (2375, 'GAV Video');
INSERT INTO studio (id, name) VALUES (2379, 'Scooter Films');
INSERT INTO studio (id, name) VALUES (2387, 'Ga-Crew');
INSERT INTO studio (id, name) VALUES (2388, 'Ai Yume Mai');
INSERT INTO studio (id, name) VALUES (2389, 'G.P Entertainment');
INSERT INTO studio (id, name) VALUES (2390, 'Concept Films');
INSERT INTO studio (id, name) VALUES (2391, 'Sumomo Film');
INSERT INTO studio (id, name) VALUES (2392, 'Ishibashi Planning');
INSERT INTO studio (id, name) VALUES (2393, 'MB planning');
INSERT INTO studio (id, name) VALUES (2394, 'MoMo Production');
INSERT INTO studio (id, name) VALUES (2395, 'J.C.F.');
INSERT INTO studio (id, name) VALUES (2396, 'Joicy Studio');
INSERT INTO studio (id, name) VALUES (2397, 'Pink Cat');
INSERT INTO studio (id, name) VALUES (2398, 'VCRWORKS');
INSERT INTO studio (id, name) VALUES (2399, 'Eshoya Honpo');
INSERT INTO studio (id, name) VALUES (2400, 'Executive Decision');
INSERT INTO studio (id, name) VALUES (2401, 'YURUPPE Inc.');
INSERT INTO studio (id, name) VALUES (2403, 'Brians Film');
INSERT INTO studio (id, name) VALUES (2405, 'Staple Entertainment');
INSERT INTO studio (id, name) VALUES (2406, 'Eallin');
INSERT INTO studio (id, name) VALUES (2407, 'Flying Ship Studio');
INSERT INTO studio (id, name) VALUES (2409, 'Amineworks');
INSERT INTO studio (id, name) VALUES (2410, 'Gonzino');
INSERT INTO studio (id, name) VALUES (2411, 'Studio Massket');
INSERT INTO studio (id, name) VALUES (2412, 'FUNNY MOVIE');
INSERT INTO studio (id, name) VALUES (2413, 'AION Studio');
INSERT INTO studio (id, name) VALUES (2414, 'MontBlanc Pictures');
INSERT INTO studio (id, name) VALUES (2415, 'HuaMei Animation');
INSERT INTO studio (id, name) VALUES (2416, 'Kent House');
INSERT INTO studio (id, name) VALUES (2418, 'Imagica Digitalscape');
INSERT INTO studio (id, name) VALUES (2419, 'd00r works');
INSERT INTO studio (id, name) VALUES (2420, 'Tang Kirin Culture');
INSERT INTO studio (id, name) VALUES (2421, 'M&M');
INSERT INTO studio (id, name) VALUES (2424, 'Bandai Namco Filmworks');
INSERT INTO studio (id, name) VALUES (2429, 'STUDIO6''oN');
INSERT INTO studio (id, name) VALUES (2432, 'happyproject');
INSERT INTO studio (id, name) VALUES (2436, 'Frontier One');
INSERT INTO studio (id, name) VALUES (2437, 'Infinity Vision');
INSERT INTO studio (id, name) VALUES (2438, 'yell');
INSERT INTO studio (id, name) VALUES (2439, 'Chosen');
INSERT INTO studio (id, name) VALUES (2447, 'Youku');
INSERT INTO studio (id, name) VALUES (2449, 'Atorie A.B.C.');
INSERT INTO studio (id, name) VALUES (2450, 'C and R');
INSERT INTO studio (id, name) VALUES (2451, 'TEC');
INSERT INTO studio (id, name) VALUES (2452, 'Project Team Muu');
INSERT INTO studio (id, name) VALUES (2453, 'Kusama Art');
INSERT INTO studio (id, name) VALUES (2454, 'Ryuu M''s');
INSERT INTO studio (id, name) VALUES (2455, 'East Fish Studio');
INSERT INTO studio (id, name) VALUES (2456, 'team Yamahitsuji');
INSERT INTO studio (id, name) VALUES (2457, 'Studio Ranmaru');
INSERT INTO studio (id, name) VALUES (2459, 'Studio Gazelle');
INSERT INTO studio (id, name) VALUES (2460, 'aNCHOR');
INSERT INTO studio (id, name) VALUES (2461, 'Twenty First');
INSERT INTO studio (id, name) VALUES (2463, 'Cloud Art');
INSERT INTO studio (id, name) VALUES (2469, 'HM Heros');
INSERT INTO studio (id, name) VALUES (2471, 'Wonder Cat Animation');
INSERT INTO studio (id, name) VALUES (2472, 'High Energy Studio');
INSERT INTO studio (id, name) VALUES (2474, 'Haneda xR Studio');
INSERT INTO studio (id, name) VALUES (2478, 'Oriental Creative Color');
INSERT INTO studio (id, name) VALUES (2482, 'Atti Production');
INSERT INTO studio (id, name) VALUES (2484, 'Gunners');
INSERT INTO studio (id, name) VALUES (2486, 'Blue Note');
INSERT INTO studio (id, name) VALUES (2487, 'Kyushu Network Animation');
INSERT INTO studio (id, name) VALUES (2488, 'J.K.I');
INSERT INTO studio (id, name) VALUES (2489, 'Tsubo Production');
INSERT INTO studio (id, name) VALUES (2490, 'Studio Dolphin Night');
INSERT INTO studio (id, name) VALUES (2491, 'Mikimoto Production');
INSERT INTO studio (id, name) VALUES (2492, 'Studio Jin');
INSERT INTO studio (id, name) VALUES (2493, 'Studio B&M');
INSERT INTO studio (id, name) VALUES (2494, 'Enzo Animation');
INSERT INTO studio (id, name) VALUES (2503, '7doc');
INSERT INTO studio (id, name) VALUES (2508, 'Deck');
INSERT INTO studio (id, name) VALUES (2509, 'Colored Pencil Animation');
INSERT INTO studio (id, name) VALUES (2513, 'HMCH');
INSERT INTO studio (id, name) VALUES (2514, 'AIC Project');
INSERT INTO studio (id, name) VALUES (2520, 'Twilight Town');
INSERT INTO studio (id, name) VALUES (2521, 'Qiyuan Yinghua');
INSERT INTO studio (id, name) VALUES (2525, 'Hurray!');
INSERT INTO studio (id, name) VALUES (2526, 'Shenman Entertainment');
INSERT INTO studio (id, name) VALUES (2527, 'Liber');
INSERT INTO studio (id, name) VALUES (2528, 'Passion Paint Animation');
INSERT INTO studio (id, name) VALUES (2529, 'Xing Yi Kai Chen');
INSERT INTO studio (id, name) VALUES (2530, 'Blue bread');
INSERT INTO studio (id, name) VALUES (2534, 'studio YOG');
INSERT INTO studio (id, name) VALUES (2535, 'Uguisu Kobo');
INSERT INTO studio (id, name) VALUES (2538, 'Imagestone Inc.');
INSERT INTO studio (id, name) VALUES (2540, 'Fever Creations');
INSERT INTO studio (id, name) VALUES (2541, 'SAMG Entertainment ');
INSERT INTO studio (id, name) VALUES (2544, 'Kami Kukan');
INSERT INTO studio (id, name) VALUES (2546, 'Studio Sota');
INSERT INTO studio (id, name) VALUES (2547, 'Frontier Engine');
INSERT INTO studio (id, name) VALUES (2549, 'StudioXD');
INSERT INTO studio (id, name) VALUES (2551, 'Animation 501');
INSERT INTO studio (id, name) VALUES (2552, 'C&S Production');
INSERT INTO studio (id, name) VALUES (2553, 'Garyuu Studio');
INSERT INTO studio (id, name) VALUES (2554, 'Gekkou');
INSERT INTO studio (id, name) VALUES (2555, 'Year Young Culture');
INSERT INTO studio (id, name) VALUES (2558, 'Delpic');
INSERT INTO studio (id, name) VALUES (2559, 'Guo Pengzi Studio');
INSERT INTO studio (id, name) VALUES (2560, 'Nekonigashi Inc.');
INSERT INTO studio (id, name) VALUES (2561, 'OTOIRO');
INSERT INTO studio (id, name) VALUES (2562, 'Studio Himalaya');
INSERT INTO studio (id, name) VALUES (2563, 'Studio Tumble');
INSERT INTO studio (id, name) VALUES (2564, 'Yamiken');
INSERT INTO studio (id, name) VALUES (2569, 'Yinhe Changxing Culture');
INSERT INTO studio (id, name) VALUES (2570, 'Ijigen Tokyo');
INSERT INTO studio (id, name) VALUES (2571, 'Griot Groove');
INSERT INTO studio (id, name) VALUES (2572, 'Adonero');
INSERT INTO studio (id, name) VALUES (2574, 'Circus Production');
INSERT INTO studio (id, name) VALUES (2576, 'General Entertainment');
INSERT INTO studio (id, name) VALUES (2580, 'GUMBLAB');
INSERT INTO studio (id, name) VALUES (2591, 'Studio Pivote');
INSERT INTO studio (id, name) VALUES (2593, 'Angle');
INSERT INTO studio (id, name) VALUES (2595, 'TypeZero');
INSERT INTO studio (id, name) VALUES (2596, 'Comma Studio');
INSERT INTO studio (id, name) VALUES (2597, 'Wong Ping Animation Lab');
INSERT INTO studio (id, name) VALUES (2598, 'Bigcat Studio');
INSERT INTO studio (id, name) VALUES (2600, 'Cloud Hearts');
INSERT INTO studio (id, name) VALUES (2601, 'Sunflowers');
INSERT INTO studio (id, name) VALUES (2604, 'DC Impression Vision');
INSERT INTO studio (id, name) VALUES (2605, 'Tonari Animation');
INSERT INTO studio (id, name) VALUES (2606, 'Toyo Links Corporation');
INSERT INTO studio (id, name) VALUES (2611, 'Fantawild Animation');
INSERT INTO studio (id, name) VALUES (2612, 'Fengyun Animation');
INSERT INTO studio (id, name) VALUES (2613, 'Aurora Animation');
INSERT INTO studio (id, name) VALUES (2614, 'Chongzhuo Animation');
INSERT INTO studio (id, name) VALUES (2619, 'Quyue Technology');
INSERT INTO studio (id, name) VALUES (2622, 'Makaria');
INSERT INTO studio (id, name) VALUES (2623, 'Dyna Method');
INSERT INTO studio (id, name) VALUES (2624, 'Village Studio');
INSERT INTO studio (id, name) VALUES (2625, 'Square Pictures');
INSERT INTO studio (id, name) VALUES (2626, 'Studio D-Volt');
INSERT INTO studio (id, name) VALUES (2628, 'Xiaoming Taiji');
INSERT INTO studio (id, name) VALUES (2635, 'Escape Velocity Animation');
INSERT INTO studio (id, name) VALUES (2636, 'Qingxiang Culture');
INSERT INTO studio (id, name) VALUES (2638, 'Pure Arts');
INSERT INTO studio (id, name) VALUES (2642, 'E&H Production');
INSERT INTO studio (id, name) VALUES (2644, 'Kuai Ying Hu Yu');
INSERT INTO studio (id, name) VALUES (2645, 'Liyu Culture');
INSERT INTO studio (id, name) VALUES (2646, 'trenova');
INSERT INTO studio (id, name) VALUES (2647, 'Studio A. Craft');
INSERT INTO studio (id, name) VALUES (2648, 'Au Praxinoscope');
INSERT INTO studio (id, name) VALUES (2649, 'LB Commerce');
INSERT INTO studio (id, name) VALUES (2651, 'Stereotype');
INSERT INTO studio (id, name) VALUES (2652, 'Gravity Well');
INSERT INTO studio (id, name) VALUES (2656, 'UchuPeople');
INSERT INTO studio (id, name) VALUES (2657, 'NANON CREATIVE');
INSERT INTO studio (id, name) VALUES (2658, 'flag Co.');
INSERT INTO studio (id, name) VALUES (2660, 'Changchun Unity of Knowledge and Action Animation');
INSERT INTO studio (id, name) VALUES (2663, 'Rock''n Roll Mountain');
INSERT INTO studio (id, name) VALUES (2665, 'AMGA');
INSERT INTO studio (id, name) VALUES (2666, 'EOEO System');
INSERT INTO studio (id, name) VALUES (2667, 'Keyring');
INSERT INTO studio (id, name) VALUES (2669, 'THINGS.');
INSERT INTO studio (id, name) VALUES (2673, 'Goto Inc.');
INSERT INTO studio (id, name) VALUES (2674, 'BUG FILMS');
INSERT INTO studio (id, name) VALUES (2676, 'Pmats9 studio');
INSERT INTO studio (id, name) VALUES (2677, 'Central Animation Studio');
INSERT INTO studio (id, name) VALUES (2678, 'Slow Studio');
INSERT INTO studio (id, name) VALUES (2679, 'cogitoworks');
INSERT INTO studio (id, name) VALUES (2682, 'Steamworks');
INSERT INTO studio (id, name) VALUES (2684, 'CHOCOLATE');
INSERT INTO studio (id, name) VALUES (2686, 'EDP graphic works');
INSERT INTO studio (id, name) VALUES (2688, 'Saber Project');
INSERT INTO studio (id, name) VALUES (2692, 'Ice Butter');
INSERT INTO studio (id, name) VALUES (2693, '6pucks');
INSERT INTO studio (id, name) VALUES (2694, 'studio NAGURI');
INSERT INTO studio (id, name) VALUES (2695, 'SIGNIF');
INSERT INTO studio (id, name) VALUES (2696, '100studio');
INSERT INTO studio (id, name) VALUES (2698, 'Voil');
INSERT INTO studio (id, name) VALUES (2701, 'CMC Media');
INSERT INTO studio (id, name) VALUES (2702, 'HuaDream');
INSERT INTO studio (id, name) VALUES (2703, 'Oyster');
INSERT INTO studio (id, name) VALUES (2705, 'TOHO animation STUDIO');
INSERT INTO studio (id, name) VALUES (2706, 'Hananona Studio');
INSERT INTO studio (id, name) VALUES (2711, 'Miyu Productions');
INSERT INTO studio (id, name) VALUES (2713, 'Infinity Animations');
INSERT INTO studio (id, name) VALUES (2714, 'evg');
INSERT INTO studio (id, name) VALUES (2715, 'Hand to Mouse.');
INSERT INTO studio (id, name) VALUES (2721, 'NHK Art');
INSERT INTO studio (id, name) VALUES (2722, 'Studio Fusion');
INSERT INTO studio (id, name) VALUES (2723, 'Unend');
INSERT INTO studio (id, name) VALUES (2724, 'Heart & Soul Animation');
INSERT INTO studio (id, name) VALUES (2725, 'CompTown');
INSERT INTO studio (id, name) VALUES (2726, 'Laftel');
INSERT INTO studio (id, name) VALUES (2728, 'New Deer');
INSERT INTO studio (id, name) VALUES (2729, 'CANON RECORDINGS');
INSERT INTO studio (id, name) VALUES (2742, 'Studio N');
INSERT INTO studio (id, name) VALUES (2743, 'Shengguang Knight Culture');
INSERT INTO studio (id, name) VALUES (2744, 'Hong Ying Animation');
INSERT INTO studio (id, name) VALUES (2746, 'Studio Vandal');
INSERT INTO studio (id, name) VALUES (2748, 'Sankaku');
INSERT INTO studio (id, name) VALUES (2749, 'Anime Tokyo');
INSERT INTO studio (id, name) VALUES (2750, 'Hu Po Donghua');
INSERT INTO studio (id, name) VALUES (2754, 'Contrail');
INSERT INTO studio (id, name) VALUES (2755, 'Congrong Film');
INSERT INTO studio (id, name) VALUES (2757, 'Caviar');
INSERT INTO studio (id, name) VALUES (2760, 'Studio Add');
INSERT INTO studio (id, name) VALUES (2761, 'ARCUS');
INSERT INTO studio (id, name) VALUES (2762, 'Studio Matomo');
INSERT INTO studio (id, name) VALUES (2764, 'Studio HUIT');
INSERT INTO studio (id, name) VALUES (2765, 'Bebow');
INSERT INTO studio (id, name) VALUES (2767, 'Euluca Lab');
INSERT INTO studio (id, name) VALUES (2772, 'Misogo Animation Studio');
INSERT INTO studio (id, name) VALUES (2773, 'Transistor Studio');
INSERT INTO studio (id, name) VALUES (2774, 'Shadow Steps');
INSERT INTO studio (id, name) VALUES (2775, 'Production Wave');
INSERT INTO studio (id, name) VALUES (2778, 'Sasayuri');
INSERT INTO studio (id, name) VALUES (2779, 'Studio BAZOOKA');
INSERT INTO studio (id, name) VALUES (2780, 'Studio Artegg');
INSERT INTO studio (id, name) VALUES (2781, 'Cloud Culture');
INSERT INTO studio (id, name) VALUES (2783, 'ANYZAC');
INSERT INTO studio (id, name) VALUES (2784, 'Medo');
INSERT INTO studio (id, name) VALUES (2785, 'Shikachan Studio');
INSERT INTO studio (id, name) VALUES (2787, 'Studio Lemon');
INSERT INTO studio (id, name) VALUES (2790, 'Hezmon Animation');
INSERT INTO studio (id, name) VALUES (2792, 'INTERFACEDOGS');
INSERT INTO studio (id, name) VALUES (2794, 'BUDDHA INC.');
INSERT INTO studio (id, name) VALUES (2795, 'Xing Xing Donghua');
INSERT INTO studio (id, name) VALUES (2802, 'Yudubai Animation');
INSERT INTO studio (id, name) VALUES (2807, 'ABJ COMPANY');
INSERT INTO studio (id, name) VALUES (2809, 'PHANTOM');
INSERT INTO studio (id, name) VALUES (2810, 'Studio Yona');
INSERT INTO studio (id, name) VALUES (2812, 'Zuiyo');
INSERT INTO studio (id, name) VALUES (2813, 'Iconix Entertainment');
INSERT INTO studio (id, name) VALUES (2814, 'Image Studio 109');
INSERT INTO studio (id, name) VALUES (2818, 'qmotri');
INSERT INTO studio (id, name) VALUES (2819, 'soket');
INSERT INTO studio (id, name) VALUES (2820, 'maroyaka');
INSERT INTO studio (id, name) VALUES (2821, 'Fugaku');
INSERT INTO studio (id, name) VALUES (2822, 'Shykeumo Animation Studio');
INSERT INTO studio (id, name) VALUES (2824, 'Production HASU');
INSERT INTO studio (id, name) VALUES (2828, 'Studio Polon');
INSERT INTO studio (id, name) VALUES (2829, 'EOTA');
INSERT INTO studio (id, name) VALUES (2830, 'Artner');
INSERT INTO studio (id, name) VALUES (2831, 'uzupiyo Animation & Digital Works');
INSERT INTO studio (id, name) VALUES (2832, 'VROOOOM');
INSERT INTO studio (id, name) VALUES (2833, 'Sofix');
INSERT INTO studio (id, name) VALUES (2834, 'Hero');
INSERT INTO studio (id, name) VALUES (2835, 'ROLL2');
INSERT INTO studio (id, name) VALUES (2842, 'Big Pine Animation Studio');
INSERT INTO studio (id, name) VALUES (2844, 'Imagica Infos');
INSERT INTO studio (id, name) VALUES (2845, 'Dimps');
INSERT INTO studio (id, name) VALUES (2846, 'Studio Bingo');
INSERT INTO studio (id, name) VALUES (2848, 'Taiko Studios');
INSERT INTO studio (id, name) VALUES (2850, 'SAFEHOUSE Inc.');
INSERT INTO studio (id, name) VALUES (2853, 'ASTROBROS.');
INSERT INTO studio (id, name) VALUES (2854, 'Volca');
INSERT INTO studio (id, name) VALUES (2855, 'Studio Moe');
INSERT INTO studio (id, name) VALUES (2857, 'CELAVIE');
INSERT INTO studio (id, name) VALUES (2858, 'Makino Production');
INSERT INTO studio (id, name) VALUES (2859, '924 Studio');
INSERT INTO studio (id, name) VALUES (2860, 'CANOPUS');
INSERT INTO studio (id, name) VALUES (2861, 'KWANED');
INSERT INTO studio (id, name) VALUES (2863, 'Miota');
INSERT INTO studio (id, name) VALUES (2864, 'Windy Studio');
INSERT INTO studio (id, name) VALUES (2870, 'Alke');
INSERT INTO studio (id, name) VALUES (2875, 'Blaze Studio');
INSERT INTO studio (id, name) VALUES (2877, 'D''ART Shtajio');
INSERT INTO studio (id, name) VALUES (2878, 'Khaki');
INSERT INTO studio (id, name) VALUES (2879, 'Grayscale Arts');
INSERT INTO studio (id, name) VALUES (2880, 'ORCEN');
INSERT INTO studio (id, name) VALUES (2881, 'Andraft');
INSERT INTO studio (id, name) VALUES (2882, 'THREE IS A MAGIC NUMBER');
INSERT INTO studio (id, name) VALUES (2883, 'Atelier Tuki');
INSERT INTO studio (id, name) VALUES (2885, 'Group Creato');
INSERT INTO studio (id, name) VALUES (2888, 'Wang Film Productions');
INSERT INTO studio (id, name) VALUES (2891, 'A4A Inc.');
INSERT INTO studio (id, name) VALUES (2893, 'Gear Studio');
INSERT INTO studio (id, name) VALUES (2894, 'Konami animation');
INSERT INTO studio (id, name) VALUES (2895, 'Team OneOne');
INSERT INTO studio (id, name) VALUES (2897, 'MOJO Animation');
INSERT INTO studio (id, name) VALUES (2898, 'Manaa Animation');
INSERT INTO studio (id, name) VALUES (2906, 'Kobito');
INSERT INTO studio (id, name) VALUES (2907, 'Studio Placebo');
INSERT INTO studio (id, name) VALUES (2909, 'Teddy');
INSERT INTO studio (id, name) VALUES (2911, 'Studio Eight Color');
INSERT INTO studio (id, name) VALUES (2914, 'Creative House Pocket');
INSERT INTO studio (id, name) VALUES (2916, 'Reirs');
INSERT INTO studio (id, name) VALUES (2917, 'Soigne');
INSERT INTO studio (id, name) VALUES (2919, 'Le-joy Animation Studio');
INSERT INTO studio (id, name) VALUES (2921, 'Public Enemies');
INSERT INTO studio (id, name) VALUES (2928, 'Elias');
INSERT INTO studio (id, name) VALUES (2931, 'Buyuu');
INSERT INTO studio (id, name) VALUES (2933, 'Hutoon Animation');
INSERT INTO studio (id, name) VALUES (2934, 'studio2 Animation Lab');
INSERT INTO studio (id, name) VALUES (2936, 'G&G Direction');
INSERT INTO studio (id, name) VALUES (2938, '3D Co.');
INSERT INTO studio (id, name) VALUES (2939, 'Studio Gale');
INSERT INTO studio (id, name) VALUES (2940, 'Ocon Studio');
INSERT INTO studio (id, name) VALUES (2944, 'Brick Studio');
INSERT INTO studio (id, name) VALUES (2945, 'Studio Goindol');
INSERT INTO studio (id, name) VALUES (2947, 'Tokyo TV Douga');
INSERT INTO studio (id, name) VALUES (2948, 'Nippon TV Douga');
INSERT INTO studio (id, name) VALUES (2950, 'studio ALBLE');
INSERT INTO studio (id, name) VALUES (2951, 'Pierrot Films');
INSERT INTO studio (id, name) VALUES (2953, 'Flying Monkeys Production');
INSERT INTO studio (id, name) VALUES (2954, 'Studio Button');
INSERT INTO studio (id, name) VALUES (2955, 'Sunny Gapen');
INSERT INTO studio (id, name) VALUES (2957, 'Particlefield');
INSERT INTO studio (id, name) VALUES (2967, 'Digital Dream Studios');
INSERT INTO studio (id, name) VALUES (2969, 'Mainichi Eigasha');
INSERT INTO studio (id, name) VALUES (2970, '717 Animation Studio');
INSERT INTO studio (id, name) VALUES (2972, 'Cocktail Media');