
CREATE TABLE IF NOT EXISTS genre(
    id int primary key not null,
    name text
);
                
INSERT INTO genre (id, name) VALUES (1, 'Action');
INSERT INTO genre (id, name) VALUES (2, 'Adventure');
INSERT INTO genre (id, name) VALUES (3, 'Racing');
INSERT INTO genre (id, name) VALUES (4, 'Comedy');
INSERT INTO genre (id, name) VALUES (5, 'Avant Garde');
INSERT INTO genre (id, name) VALUES (6, 'Mythology');
INSERT INTO genre (id, name) VALUES (7, 'Mystery');
INSERT INTO genre (id, name) VALUES (8, 'Drama');
INSERT INTO genre (id, name) VALUES (9, 'Ecchi');
INSERT INTO genre (id, name) VALUES (10, 'Fantasy');
INSERT INTO genre (id, name) VALUES (11, 'Strategy Game');
INSERT INTO genre (id, name) VALUES (12, 'Hentai');
INSERT INTO genre (id, name) VALUES (13, 'Historical');
INSERT INTO genre (id, name) VALUES (14, 'Horror');
INSERT INTO genre (id, name) VALUES (15, 'Kids');
INSERT INTO genre (id, name) VALUES (17, 'Martial Arts');
INSERT INTO genre (id, name) VALUES (18, 'Mecha');
INSERT INTO genre (id, name) VALUES (19, 'Music');
INSERT INTO genre (id, name) VALUES (20, 'Parody');
INSERT INTO genre (id, name) VALUES (21, 'Samurai');
INSERT INTO genre (id, name) VALUES (22, 'Romance');
INSERT INTO genre (id, name) VALUES (23, 'School');
INSERT INTO genre (id, name) VALUES (24, 'Sci-Fi');
INSERT INTO genre (id, name) VALUES (25, 'Shoujo');
INSERT INTO genre (id, name) VALUES (26, 'Girls Love');
INSERT INTO genre (id, name) VALUES (27, 'Shounen');
INSERT INTO genre (id, name) VALUES (28, 'Boys Love');
INSERT INTO genre (id, name) VALUES (29, 'Space');
INSERT INTO genre (id, name) VALUES (30, 'Sports');
INSERT INTO genre (id, name) VALUES (31, 'Super Power');
INSERT INTO genre (id, name) VALUES (32, 'Vampire');
INSERT INTO genre (id, name) VALUES (35, 'Harem');
INSERT INTO genre (id, name) VALUES (36, 'Slice of Life');
INSERT INTO genre (id, name) VALUES (37, 'Supernatural');
INSERT INTO genre (id, name) VALUES (38, 'Military');
INSERT INTO genre (id, name) VALUES (39, 'Detective');
INSERT INTO genre (id, name) VALUES (40, 'Psychological');
INSERT INTO genre (id, name) VALUES (41, 'Suspense');
INSERT INTO genre (id, name) VALUES (42, 'Seinen');
INSERT INTO genre (id, name) VALUES (43, 'Josei');
INSERT INTO genre (id, name) VALUES (46, 'Award Winning');
INSERT INTO genre (id, name) VALUES (47, 'Gourmet');
INSERT INTO genre (id, name) VALUES (48, 'Workplace');
INSERT INTO genre (id, name) VALUES (49, 'Erotica');
INSERT INTO genre (id, name) VALUES (50, 'Adult Cast');
INSERT INTO genre (id, name) VALUES (51, 'Anthropomorphic');
INSERT INTO genre (id, name) VALUES (52, 'CGDCT');
INSERT INTO genre (id, name) VALUES (53, 'Childcare');
INSERT INTO genre (id, name) VALUES (54, 'Combat Sports');
INSERT INTO genre (id, name) VALUES (55, 'Delinquents');
INSERT INTO genre (id, name) VALUES (56, 'Educational');
INSERT INTO genre (id, name) VALUES (57, 'Gag Humor');
INSERT INTO genre (id, name) VALUES (58, 'Gore');
INSERT INTO genre (id, name) VALUES (59, 'High Stakes Game');
INSERT INTO genre (id, name) VALUES (60, 'Idols (Female)');
INSERT INTO genre (id, name) VALUES (61, 'Idols (Male)');
INSERT INTO genre (id, name) VALUES (62, 'Isekai');
INSERT INTO genre (id, name) VALUES (63, 'Iyashikei');
INSERT INTO genre (id, name) VALUES (64, 'Love Polygon');
INSERT INTO genre (id, name) VALUES (65, 'Magical Sex Shift');
INSERT INTO genre (id, name) VALUES (66, 'Mahou Shoujo');
INSERT INTO genre (id, name) VALUES (67, 'Medical');
INSERT INTO genre (id, name) VALUES (68, 'Organized Crime');
INSERT INTO genre (id, name) VALUES (69, 'Otaku Culture');
INSERT INTO genre (id, name) VALUES (70, 'Performing Arts');
INSERT INTO genre (id, name) VALUES (71, 'Pets');
INSERT INTO genre (id, name) VALUES (72, 'Reincarnation');
INSERT INTO genre (id, name) VALUES (73, 'Reverse Harem');
INSERT INTO genre (id, name) VALUES (74, 'Romantic Subtext');
INSERT INTO genre (id, name) VALUES (75, 'Showbiz');
INSERT INTO genre (id, name) VALUES (76, 'Survival');
INSERT INTO genre (id, name) VALUES (77, 'Team Sports');
INSERT INTO genre (id, name) VALUES (78, 'Time Travel');
INSERT INTO genre (id, name) VALUES (79, 'Video Game');
INSERT INTO genre (id, name) VALUES (80, 'Visual Arts');
INSERT INTO genre (id, name) VALUES (81, 'Crossdressing');